### ISSUE TITLE
Missing packages in package.json

### ISSUE THREAD

**Issue by ruslanguns** [marcomelilli/nestjs-email-authentication#2]
Looks like there are missing packages of modules in your project. 

BY THE WAY, any plan to upgrade it to version 6+?

ALSO, why do you use var in too many variable? I just want to understand a little bit about your point of view, I know there's no must of only using let and const, just consider this question as for educational purposes.

**Comment by marcomelilli** [comment]
Thank you! I added packages in the package.json and fix missing modules.
Anyway In this moment I don't have plans: I used this starter for another project and decided to share... I don't know if I will upgrade or add new features.
About the "var", you are right it's correct use "let" in that case.. It's only a bad habits :)

**Comment by marcomelilli** [comment]
@ruslanguns Hi! I'm upgrading the project in this branch: https://github.com/marcomelilli/nestjs-email-authentication/tree/migration-v6 . I will merge it into the master if everything works well

**Comment by ruslanguns** [comment]
@marcomelilli  cool. I very liked this project and served to me for introduction for a couple projects on which I am working. So thanks for keeping updating it.
