### ISSUE TITLE
nestjs v6 compatible ?

### ISSUE THREAD

**Issue by whois0xio** [marcomelilli/nestjs-email-authentication#4]

**Comment by marcomelilli** [comment]
Hi, not yet. As soon as I can I will migrate the project to nestjs v6

**Comment by marcomelilli** [comment]
@whois0xio I'm upgrading the project in this branch: https://github.com/marcomelilli/nestjs-email-authentication/tree/migration-v6 . I will merge it into the master if everything works well

**Comment by ellis2323** [comment]
Thx
