### ISSUE TITLE
Strange error after clone

### ISSUE THREAD

**Issue by Dugnist** [marcomelilli/nestjs-email-authentication#6]
![image](https://user-images.githubusercontent.com/6489460/70958267-607e9580-2081-11ea-8777-7574fa68e710.png)
![image](https://user-images.githubusercontent.com/6489460/70958284-6bd1c100-2081-11ea-987a-b0e9f5c3f1b9.png)
![image](https://user-images.githubusercontent.com/6489460/70958327-96bc1500-2081-11ea-85f6-6437e913853c.png)

**Comment by marcomelilli** [comment]
Very strange... which version of nodejs are you using?
From logs seems that the problem is on the express-rate-limit module. You can try to remove it from: "/src/main.ts" deleting the two "app.use(...)" containing "rateLimit" and "createAccountLimiter"

**Comment by Dugnist** [comment]
@marcomelilli 
![image](https://user-images.githubusercontent.com/6489460/70996879-66ee2b00-20dc-11ea-8f12-b6ca5c896bc9.png)

It's a strange behavior but today it auto fixed xD

![image](https://user-images.githubusercontent.com/6489460/70997116-f267bc00-20dc-11ea-873a-5feeb87105eb.png)

**Comment by Dugnist** [comment]
Maybe some modules required a reboot system...

**Comment by marcomelilli** [comment]
Great, I'm glad it works :)
