### ISSUE TITLE
error TS2769: No overload matches this call.

### ISSUE THREAD

**Issue by omnecon** [marcomelilli/nestjs-email-authentication#7]
This project is looking very promissing. Sadly I run into the following build-issue:

```
TSError: ⨯ Unable to compile TypeScript:
src/auth/auth.service.ts:49:11 - error TS2769: No overload matches this call.
  The last overload gave the following error.
    Type 'number' is not assignable to type 'string'.

49           emailToken: Math.floor(Math.random() * (9000000)) + 1000000, //Generate 7 digits number
```

I am running node v13.1.0 on Windows. What could be the issue?

**Comment by marcomelilli** [comment]
mm.. it's a typescript error because emailToken is defined as string. Try to replace that row with:

```
emailToken: (Math.floor(Math.random() * (9000000)) + 1000000).toString(), //Generate 7 digits number
```

**Comment by omnecon** [comment]
Yes, you were right. This trick fixed this and another issue of the same kind. I opened a PR https://github.com/marcomelilli/nestjs-email-authentication/pull/8
