### ISSUE TITLE
npm run start

### ISSUE THREAD

**Issue by msimonc** [marcomelilli/nestjs-email-authentication#9]
`TSError: ⨯ Unable to compile TypeScript:
src/users/schemas/user.schema.ts:13:3 - error TS2322: Type 'String[]' is not assignable to type 'string | Function | Schema | SchemaDefinition | SchemaTypeOptions<any> | Schema[] | SchemaTypeOptions<any>[] | Function[] | SchemaDefinition[]'.
  Type 'String[]' is not assignable to type 'Schema[]'.
    Type 'String' is missing the following properties from type 'Schema': add, clone, eachPath, index, and 35 more.

13   roles: Array<String>(),
     ~~~~~

  node_modules/mongoose/index.d.ts:1116:5
    1116     [path: string]: SchemaTypeOptions<any> | Function | string | Schema | Schema[] | Array<SchemaTypeOptions<any>> | Function[] | SchemaDefinition | SchemaDefinition[];
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    The expected type comes from this index signature.
`

Thanks,

**Comment by marcomelilli** [comment]
Hi msimonc, thank you for the bug report. I just commited the fix. Let me know if everithing is ok
